version: '3.7'

services:
  node1:
    image: mongo
    ports:
      - 30001:27071
    volumes:
      - mongodb_data_container1:/data/db
    networks:
      - mongocluster
    command: mongod --replSet comments
  node2:
    image: mongo
    ports:
      - 30002:27071
    volumes:
      - mongodb_data_container2:/data/db
    networks:
      - mongocluster
    command: mongod --replSet comments
    depends_on :
      - node1
  node3:
    image: mongo
    ports:
      - 30003:27071
    volumes:
      - mongodb_data_container3:/data/db
    networks:
      - mongocluster
    command: mongod --replSet comments
    depends_on :
      - node2

networks:
  mongocluster:
    driver: bridge

volumes:
  mongodb_data_container1:
  mongodb_data_container2:
  mongodb_data_container3:
